name: coc-explorer CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [16]

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      # - uses: rhysd/action-setup-vim@v1
      #   with:
      #     neovim: true
      #     version: v0.7.0
      - run: yarn test
        env:
          NODE_ENV: test
